'use client'
import { ApolloProvider } from '@apollo/client'
import './globals.css'
import { Inter } from 'next/font/google'
import client from './config/apollo-client'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"
      className="h-full bg-white"
    >

      <body className='h-full'>
        <ApolloProvider client={client}>
          {children}
        </ApolloProvider>

      </body>
    </html>
  )
}
